server:
    port: 8080
    servlet:
        context-path: ${CONTEXT_PATH:}

spring:
    application:
        name: '@name@'

    output:
        ansi:
            enabled: ALWAYS

    datasource:
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        hikari:
            maximum-pool-size: 2
            minimum-idle: 2

    jpa:
        open-in-view: false
        show-sql: false
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                order_inserts: true
                default_schema: blog_app
                format_sql: true
                jdbc:
                batch_size: 100


    liquibase:
        enabled: true
        change-log: classpath:/db/changelog/db.changelog-master.yml
        default-schema: blog_app
